
title                    : "Lakesh Kumar Suryadevara"


# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Susan Paudel"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Earth"
  employer         : "Red Brick University"
  uri              : # URL
  email            : "susan.paudel@example.com"  # Your email here

  # LinkedIn Profile
  linkedin         : "https://www.linkedin.com/in/susan-paudel"  # Replace with your LinkedIn URL
  phone            : "+1234567890"  # Replace with your phone number
theme: jekyll-theme-minimal
